services:
  mysql:
    container_name: mysql
    image: mysql:8.4.1
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    #      - 'MYSQL_USER=user'
    ports:
      - ${DB_PORT}:3306
  redis:
    container_name: redis
    image: redis:7.2.4
    restart: no
    ports:
      - ${RD_PORT}:6379
#  api-service:
#    container_name: api-service
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: no
#    ports:
#      - ${API_PORT}:8080
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_NAME=${DB_NAME}
#      - RD_HOST=${RD_HOST}
#      - RD_PORT=${RD_PORT}
#      - JWT_SECRET=${JWT_SECRET}
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#      - AWS_REGION=${AWS_REGION}
#      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
#      - GM_USERNAME=${GM_USERNAME}
#      - GM_PASSWORD=${GM_PASSWORD}
#      - FRONT_END_DOMAIN=${FRONT_END_DOMAIN}
#    depends_on:
#      - mysql
#      - redis
#  ngrok:
#    image: ngrok/ngrok:latest
#    restart: unless-stopped
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - 4040:4040